### ISSUE TITLE
Widget Request: - record type

### ISSUE THREAD

**Issue by datalover916** [tarakc02/getcdw#8]
I would like to search for alums in X geo area without having to say alums of college or major in x.  I imagine Iberia would like to be able to isolate parents as well.  Can we add a record type widget or some such thing?

Should I move this to the projects tab?

**Comment by tarakc02** [comment]
No need to move the issue, this is fine. For future issues if they arise from the discoveryengine, it'll be better to track those there (https://github.com/tarakc02/discoveryengine/issues), to make it easier for anyone else who notices the problem to be able to see it. But I'll go ahead and get started on this since it should be a pretty quick update. Note that there is a way to get what you want already, though probably not as intuitive as record type: just use `has_degree_from()` without any schools. `?has_degree_from` mentions that " If no majors/schools are entered, the widget will look for anyone with a Cal degree (or if attendees = TRUE, anyone who has attended Cal)." So you can just type `has_degree_from()` to get anyone who is an alum, or if you just want undergraduates you can do `has_degree_from(graduates = FALSE)` or if you want to include attendees you can do `has_degree_from(attendees = TRUE)` etc.. 

Similarly, if you want to, say, look for degreeholders in San Diego, then: `has_degree_from() %and% lives_in_msa(san_diego)` or something similar . . ..
